name: Create a versioned release

on:
  push:
    tags:
      - "v[0-9]+.*"

  workflow_dispatch: # trigger manually
    inputs:
      debugger_version:
        description: "FastEdge-debugger version"
        required: true
        default: "latest"
      tag_version:
        description: "Release tag e.g. v1.0.1"
        required: true
        default: ""

permissions:
  contents: write # Required to create releases and push tags

jobs:
  check_tags:
    runs-on: [self-hosted, ubuntu-22-04, regular]
    outputs:
      has_release_tag: ${{ steps.determine-tag.outputs.has_tag }}

    steps:
      - name: Validate release tag
        id: determine-tag
        run: |
          if [ -n "${{ github.event.inputs.tag_version }}" ]; then
            TAG_VERSION="${{ github.event.inputs.tag_version }}"
          else
            TAG_VERSION=${GITHUB_REF#refs/tags/}
          fi
          if [[ ! "$TAG_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$ ]]; then
            echo "Invalid tag format: $TAG_VERSION"
            exit 1
          fi
          echo "has_tag=true" >> $GITHUB_OUTPUT
          echo "Determined release tag: $TAG_VERSION"

  fossa:
    uses: ./.github/workflows/fossa.yaml
    needs: [check_tags]
    secrets:
      FOSSA_PUB_API_KEY: ${{ secrets.FOSSA_PUB_API_KEY }}

  download_and_filter_debugger:
    uses: ./.github/workflows/download-debugger.yml
    needs: [check_tags]
    if: ${{ needs.check_tags.outputs.has_release_tag == 'true' }}
    with:
      debugger_version: ${{ inputs.debugger_version }}

  build_linux_extension:
    uses: ./.github/workflows/build-extension.yml
    needs: ["fossa", "check_tags", "download_and_filter_debugger"]
    if: ${{ needs.check_tags.outputs.has_release_tag == 'true' }}
    with:
      os_target: linux-x64
      os_name: ubuntu-latest
      tag_version: ${{ github.event.inputs.tag_version || github.ref_name }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  build_darwin_extension:
    uses: ./.github/workflows/build-extension.yml
    needs: ["build_linux_extension"]
    if: ${{ needs.check_tags.outputs.has_release_tag == 'true' }}
    with:
      os_target: darwin-arm64
      os_name: macos-latest
      tag_version: ${{ github.event.inputs.tag_version || github.ref_name }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  build_windows_extension:
    uses: ./.github/workflows/build-extension.yml
    needs: ["build_darwin_extension"]
    if: ${{ needs.check_tags.outputs.has_release_tag == 'true' }}
    with:
      os_target: win32-x64
      os_name: windows-latest
      tag_version: ${{ github.event.inputs.tag_version || github.ref_name }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
